# Generated by Django 4.2.27 on 2025-12-05 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this webhook", max_length=255
                    ),
                ),
                ("url", models.URLField(help_text="Target URL for webhook delivery")),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("import.completed", "Import Completed"),
                            ("import.failed", "Import Failed"),
                            ("product.created", "Product Created"),
                            ("product.updated", "Product Updated"),
                            ("product.deleted", "Product Deleted"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret key for HMAC signature (optional)",
                        max_length=255,
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhook",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Webhook deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["event", "enabled"], name="webhooks_we_event_367fd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["webhook", "-created_at"], name="webhooks_we_webhook_8d7634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["success"], name="webhooks_we_success_d7f4a0_idx"
            ),
        ),
    ]
