# Generated by Django 4.2.27 on 2025-12-05 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.TextField()),
                (
                    "file_key",
                    models.TextField(help_text="Storage key for the uploaded file"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_upload", "Pending Upload"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_upload",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        default="pending",
                        help_text="Current processing stage",
                        max_length=50,
                    ),
                ),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                ("processed_rows", models.IntegerField(default=0)),
                ("created_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField()),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_errors",
                        to="products.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=255)),
                (
                    "sku_normalized",
                    models.CharField(
                        db_index=True,
                        help_text="Lowercase version of SKU for case-insensitive uniqueness",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sku_normalized"], name="products_pr_sku_nor_b82c81_idx"
                    ),
                    models.Index(
                        fields=["active"], name="products_pr_active_7d1f9b_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="products_pr_created_bce1a7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["status"], name="products_im_status_3087cd_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["-created_at"], name="products_im_created_f59524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importerror",
            index=models.Index(
                fields=["job", "row_number"], name="products_im_job_id_a44aa9_idx"
            ),
        ),
    ]
