# Generated by Django 4.2.27 on 2025-12-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Last import job that created or updated this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.importjob",
            ),
        ),
    ]
