# Generated by Django 4.2.27 on 2025-12-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_last_import_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="last_import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="The import job that last created or updated this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_products",
                to="products.importjob",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["last_import_job"], name="products_pr_last_im_379286_idx"),
        ),
    ]
